language: java
install: true

jdk:
- oraclejdk8

stages:
- name: build
- name: snapshot
  if: branch = master AND type IN (push)
- name: release
  if: branch = release AND type IN (push)

jobs:
  include:
  - stage: build
    script: ./gradlew -s build
  - stage: snapshot
    script: ./gradlew publish
  - stage: release
    script: ./gradlew publish -Drelease=true

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
